module-name: telemetry-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:v20230728-aaf03794
  - europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.81.0-aee4f05f
  - europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.1.7-bcac7090
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20230607-7cc7ffbf
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
