module-name: telemetry-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:v20230609-acb0bb06
  - europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.79.0-0065b2a5
  - europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.1.2-0065b2a5
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20230503-c10c571f
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "/test"
    - "*_test.go"
