module-name: telemetry-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:v20230704-76ba9dbc
  - europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.79.0-3b3cb87a
  - europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.1.4-fef25e9c
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20230503-c10c571f
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
